# spec2pr workflow for target repositories
# Copy this file to .github/workflows/spec2pr.yml in your repository

name: spec2pr

on:
  issues:
    types: [labeled]

jobs:
  spec2pr:
    # Only run when the spec2pr/run label is added
    # Don't run on pull request comments (issues.pull_request is set for PRs)
    if: |
      github.event.label.name == 'spec2pr/run' &&
      !github.event.issue.pull_request &&
      github.event.repository.fork == false

    uses: andreikorchagin/spec2pr/.github/workflows/spec2pr.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      target_repo: ${{ github.repository }}
    secrets: inherit
